// Collo compatibility contract derived from Bun v1.3.14:
// - reference/bun-v1.3.14/test/js/web/web-globals.test.js

test("currently implemented globals exist", () => {
  for (const name of [
    "URL",
    "URLSearchParams",
    "URLPattern",
    "DOMException",
    "Event",
    "CustomEvent",
    "MessageEvent",
    "MessageChannel",
    "MessagePort",
    "ErrorEvent",
    "CloseEvent",
    "EventTarget",
    "addEventListener",
    "removeEventListener",
    "dispatchEvent",
    "onerror",
    "onmessage",
    "Performance",
    "PerformanceEntry",
    "PerformanceMark",
    "PerformanceMeasure",
    "PerformanceTiming",
    "PerformanceObserver",
    "PerformanceObserverEntryList",
    "performance",
    "Blob",
    "File",
    "FormData",
    "crypto",
    "Crypto",
    "SubtleCrypto",
    "CryptoKey",
    "Headers",
    "Request",
    "Response",
    "fetch",
    "setTimeout",
    "setInterval",
    "setImmediate",
    "clearTimeout",
    "clearInterval",
    "clearImmediate",
    "queueMicrotask",
    "atob",
    "btoa",
    "structuredClone",
    "reportError",
    "navigator",
    "console",
  ]) {
    assert(typeof globalThis[name] !== "undefined", `${name} should exist`);
  }
});
